FROM python:2.7-slim
# Install R and its meta package
RUN apt-get update
RUN apt-get install -y r-base-core
RUN bash -c "echo 'install.packages(\"meta\",repos=\"http://cran.rstudio.com/\")' | R --no-save"
# Install Python deps
RUN mkdir -p /app/user /app/logs
WORKDIR /app/user
RUN pip install --upgrade pip
ADD requirements.txt /app/user/requirements.txt
RUN apt-get install -y libpq-dev
RUN mkdir /src
RUN pip install --src /src -r requirements.txt
# Add code
ADD . /app/user
EXPOSE 8000
